export const assets = {
    Hat: "./hat.png",
    Mushroom_eyeless: "./mushroom_eyeless.png",
    Mushroom_eyes: "./mushroom_eyes.png",
    Pipe: "./pipe.png",
    RobotWalk0: "./character_robot_walk0.png",
    RobotWalk1: "./character_robot_walk1.png",
    RobotWalk2: "./character_robot_walk2.png",
    RobotWalk3: "./character_robot_walk3.png",
    RobotWalk4: "./character_robot_walk4.png",
    RobotWalk5: "./character_robot_walk5.png",
    RobotWalk6: "./character_robot_walk6.png",
    RobotWalk7: "./character_robot_walk7.png",
    Panel: "./panel3.png",
    Square: "./Square.ttf",
    Glow: "./glow.png",
    Star: "./star.svg",
    ThreeLines: "3lines.svg",
    Next: "next.svg",
    Retry: "retry.svg"
};